version: "3.4"
services:
  app:
    build:
      args:
        user: anton
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: book-app
    container_name: book-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - book-app
  nginx:
    image: nginx:alpine
    container_name: book-app-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - book-app

networks:
  book-app:
    driver: bridge

