version: "3.4"
services:
  app:
    image: anton1307/book_managment:master
    container_name: book-app
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "80" ]
      interval: 30s
      start_period: 30s
      timeout: 10s
    deploy:
      replicas: 2
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - sessions:/var/www/html/storage/framework/sessions
      - appstorage:/var/www/html/storage/app
    env_file:
      - .env
    ports:
      - 80:80
    networks:
      - book-app
  mongodb:
    container_name: book-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=homestead
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - /usr/local/mongodb:/data/db
    ports:
      - 27017:27017
    logging:
      driver: none
    networks:
        - book-app

networks:
  book-app:
    driver: bridge
volumes:
  sessions:
  appstorage:
    driver: "local"

