
name: Book Managment Tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Up .env
      run: cp .env.example .env
    - name:  Build
      run:  docker-compose build
    - name: Build
      run: docker-compose up -d
    - name: Install composer
      run: docker-compose exec -T  app composer install
    - name: Artisan Key Genegate
      run:  docker-compose exec -T app php artisan key:generate
