
name: Book Managment Tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Up .env
      run: cp .env.example .env
    - name:  Build
      run:  docker-compose build
    - name: Install composer
      uses: php-actions/composer@v5
      with:
        php_version: 8
        composer_version: 2
    - name: Build
      run: docker-compose up -d
    - name: Artisan Key Genegate
      run:  docker-compose exec -T -u sammy  app php artisan key:generate
