
name: Book Managment Tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  TAG: ${{ github.run_number }}-${{ github.sha }}
  HOST: ${{ secrets.APP_HOST }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  PORT: 22
  USERNAME: ${{ secrets.USERNAME }}
  BUCKET_INSTANCE: 68.183.210.227
  BUCKET_INSTANCE_USER: root

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Up .env
      run: cp .env.example .env
    - name:  Build
      run:  docker-compose build
    - name: Build
      run: docker-compose up -d
    - name: composer install
      run: docker-compose exec -T app composer install
    - name: Artisan Key Genegate
      run:  docker-compose exec -T app php artisan key:generate
    - name: Test
      run:  docker-compose exec -T app php artisan test

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - name: Docker Login
      run: |
        cat ${SSH_KEY} >  ~/.ssh/id_rsa
        scp ${BUCKET_INSTANCE_USER}@${BUCKET_INSTANCE}:/root/envs/.env .env
        docker-compose build app
        rm ~/.ssh/id_rsa
    - name: Push to Registry
      run:  docker push anton1307/book_managment:latest
  deploy:
    runs-on: ubuntu-latest
    needs: publish

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        mkdir ../build
        cp -TR ./ ../build
        tar -cvf deploy.tar ../build/
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${HOST}
        username: ${USERNAME}
        key: ${SSH_KEY}
        port: ${PORT}
        source: "./deploy.tar"
        target: "~/"

    - name: start project
      uses: appleboy/ssh-action@master
      with:
        host: ${HOST}
        username: ${USERNAME}
        key: ${SSH_KEY}
        port: ${PORT}
        envs: DOCKER_USERNAME, DOCKER_PASSWORD
        script: |
          tar -xvf "deploy.tar"
          mv "build/docker-compose.yaml" "docker-compose.yaml"
          rm deploy.tar && rm -Rf "build"
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker pull anton1307/book_managment:latest
          docker-compose up -d
          docker-compose exec -T app php artisan migrate

